---
title: "Dissertation_TimeSeries_Modeling"
author: "Sreelekshmi_Sreekumar"
date: "2023-08-16"
output:
  word_document: default
  pdf_document: default
---

```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide', fig.show='hide'}
library(forecast)
library(ggplot2)
library(urca)
```



```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide', fig.show='hide'}
kerala <- read.csv("kerala_ts.csv")
ts_kerala <- ts(kerala$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_kerala, xlab = "Year", ylab = expression(paste("PM10 level (", µg/m^3, ")"))) 
title ("Time Series Plot for Kerala")
acf(ts_kerala)
pacf(ts_kerala)
ts_kerala %>% ur.kpss() %>% summary()
ndiffs(ts_kerala)
nsdiffs(ts_kerala)
ts_kerala %>%
  stl(t.window=13, s.window="periodic", robust=TRUE) %>%
  autoplot()
ts_kerala <- ts(kerala$RSPM.PM10, start=2008, end = 2015, frequency=12)
model_ts_kerala <- auto.arima(ts_kerala ,stepwise=FALSE, approximation=FALSE)
summary(model_ts_kerala)
forecast_values <- forecast(model_ts_kerala, h = 11)
print(forecast_values)
forecast_plot <- forecast(model_ts_kerala, h = 11) %>% autoplot() +labs(y = expression(paste("PM10 level (", µg/m^3, ")")), x = "Year")   
forecast_plot
ts_kerala_final <- ts(kerala$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_kerala_final, xlab = "Year", ylab = expression(paste("PM10 level (", µg/m^3, ")")))
title = ("Time Series Plot of Kerala from Years 2008 to 2015")
AIC(model_ts_kerala)
```



```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide', fig.show='hide'}
delhi <- read.csv("delhi_ts.csv")
ts_delhi <- ts(delhi$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_delhi ,xlab = "Year", ylab = expression(paste("PM10 level (", µg/m^3, ")")))
title ("Time Series Plot for Delhi")
ts_delhi %>%
  stl(t.window=13, s.window="periodic", robust=TRUE) %>%
  autoplot()
acf(ts_delhi)
pacf(ts_delhi)
ts_delhi %>% ur.kpss() %>% summary()
ndiffs(ts_delhi)
nsdiffs(ts_delhi)
ts_delhi <- ts(delhi$RSPM.PM10, start=2008, end = 2015, frequency=12)
model_ts_delhi <- auto.arima(ts_delhi ,stepwise=FALSE, approximation=FALSE)
summary(model_ts_delhi)
AIC(model_ts_delhi)
model_ts_delhi_3 <- arima(ts_delhi , seasonal = list(order = c(1,1,1), period = 12))
summary(model_ts_delhi_3)
AIC(model_ts_delhi_3)
forecast_values <- forecast(model_ts_delhi, h = 11)
print(forecast_values)
forecast_plot <- forecast(model_ts_delhi_3, h = 11) %>% autoplot()+ labs(y = expression(paste("PM10 level (", µg/m^3, ")")), x = "Year")  
forecast_plot
ts_delhi_final <- ts(delhi$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_delhi_final,xlab = "Year", ylab = "PM10 Level")
title = ("Time Series Plot of Delhi from Years 2008 to 2015")
AIC(model_ts_delhi)
```


```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide', fig.show='hide'}
tamil_nadu <- read.csv("tamil_nadu_ts.csv")
ts_tamil_nadu <- ts(tamil_nadu$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_tamil_nadu,  xlab = "Year", ylab = expression(paste("PM10 level (", µg/m^3, ")")))
title ("Time Series Plot for Tamil Nadu")
ts_tamil_nadu %>%
  stl(t.window=13, s.window="periodic", robust=TRUE) %>%
  autoplot()
acf(ts_tamil_nadu)
pacf(ts_tamil_nadu)
ts_tamil_nadu %>% ur.kpss() %>% summary()
ndiffs(ts_tamil_nadu)
nsdiffs(ts_tamil_nadu)
ts_tamil_nadu <- ts(tamil_nadu$RSPM.PM10, start=2008, end = 2015, frequency=12)
model_ts_tamil_nadu <- auto.arima(ts_tamil_nadu ,stepwise=FALSE, approximation=FALSE)
summary(model_ts_tamil_nadu)
forecast_values <- forecast(model_ts_tamil_nadu, h = 11)
print(forecast_values)
forecast_plot <- forecast(model_ts_tamil_nadu, h = 11) %>% autoplot() +labs(y = expression(paste("PM10 level (", µg/m^3, ")")), x = "Year")
forecast_plot
ts_tamil_nadu_final <- ts(tamil_nadu$RSPM.PM10,  frequency=12)
plot(ts_tamil_nadu_final,xlab = "Year", ylab = "PM10 Level")
title = ("Time Series Plot of Tamil Nadu from Years 2008 to 2015")
AIC(model_ts_tamil_nadu)
```


```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide', fig.show='hide'}
jk <- read.csv("jammu_ts.csv")
ts_jk <- ts(jk$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_jk,  xlab = "Year", ylab = expression(paste("PM10 level (", µg/m^3, ")")))
title ("Time Series Plot for Jammu & Kashmir")
ts_jk %>%
  stl(t.window=13, s.window="periodic", robust=TRUE) %>%
  autoplot()
acf(ts_jk)
pacf(ts_jk)
ts_jk %>% ur.kpss() %>% summary()
ndiffs(ts_jk)
nsdiffs(ts_jk)
ts_jk <- ts(jk$RSPM.PM10, start=2008, end = 2015, frequency=12)
model_ts_jk <- auto.arima(ts_jk ,stepwise=FALSE, approximation=FALSE)
summary(model_ts_jk)
AIC(model_ts_jk)
model_ts_jk_1 <- arima(ts_jk , seasonal = list(order = c(0,0,2), period = 12))
summary(model_ts_jk_1)
AIC(model_ts_jk_1)
model_ts_jk_2 <- arima(ts_jk , seasonal = list(order = c(1,0,2), period = 12))
summary(model_ts_jk_2)
AIC(model_ts_jk_2)
model_ts_jk_3 <- arima(ts_jk , seasonal = list(order = c(1,1,2), period = 12))
summary(model_ts_jk_3)
AIC(model_ts_jk_3)
forecast_values <- forecast(model_ts_jk, h = 11)  
print(forecast_values)
forecast_plot <- forecast(model_ts_jk_3, h = 11) %>% autoplot()  +labs(y = expression(paste("PM10 level (", µg/m^3, ")")), x = "Year")
forecast_plot
ts_jk_final <- ts(jk$RSPM.PM10, start=2008, end = 2016, frequency=12)
plot(ts_jk_final,xlab = "Year", ylab = "PM10 Level")
title = ("Time Series Plot of Jammu & Kashmir from Years 2008 to 2015")
AIC(model_ts_jk)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}


```


```{r echo=FALSE, message=FALSE, warning=FALSE}


```


```{r echo=FALSE, message=FALSE, warning=FALSE}


```

```{r echo=FALSE, message=FALSE, warning=FALSE}


```

```{r echo=FALSE, message=FALSE, warning=FALSE}


```

```{r echo=FALSE, message=FALSE, warning=FALSE}


```
